# Random Fortune Teller Project

import random

# List of fortunes
FORTUNES = [
    "You will achieve great success soon.",
    "Beware of unexpected events.",
    "A thrilling time is in your near future.",
    "You will meet someone special.",
    "An opportunity will present itself, seize it!",
    "Expect some challenges but you will overcome them.",
    "Someone will offer you valuable advice.",
    "Good fortune is heading your way.",
    "A financial gain is in your future.",
    "A new adventure awaits you.",
    "You will face a difficult decision, choose wisely.",
    "An old friend will reconnect with you.",
    "You will find a solution to a long-standing problem.",
    "Be open to new ideas and experiences.",
    "A pleasant surprise is on its way.",
    "You will receive good news from a distant place.",
    "Trust your instincts; they will guide you well.",
    "A personal goal will soon be achieved.",
    "Your hard work will soon pay off.",
    "A new relationship is about to blossom.",
    "An unexpected gift will bring you joy.",
    "You will be recognized for your efforts.",
    "Take time to reflect on your achievements.",
    "A journey will bring new insights.",
    "Your creativity will shine through in a new way.",
    "Be patient; your efforts will be rewarded.",
    "An important change is coming your way.",
    "Your kindness will be returned to you tenfold.",
    "A great opportunity is just around the corner.",
    "You will find peace in a challenging situation.",
    "Prepare for an exciting new venture.",
    "Your enthusiasm will lead to success.",
    "A joyful event will bring happiness to your life.",
    "You will discover a hidden talent.",
    "Be ready for an unexpected twist in your journey.",
    "A cherished wish will come true.",
    "You will be pleasantly surprised by someone's gesture.",
    "A new friendship will bring you joy.",
    "Your intuition will guide you to success.",
    "A significant change in your routine is ahead.",
    "You will gain new insights into a problem.",
    "An achievement will bring you great satisfaction.",
    "Your generosity will be rewarded.",
    "You will soon experience a breakthrough.",
    "An upcoming event will bring you closer to your goals.",
    "A new perspective will lead to success.",
    "You will achieve a long-awaited goal.",
    "Your efforts will bring about positive changes.",
    "A special occasion will bring you happiness.",
    "You will receive a compliment from an unexpected source.",
    "An opportunity to learn will soon present itself.",
    "Your perseverance will lead to success.",
    "A new beginning is on the horizon.",
    "You will receive a pleasant surprise soon.",
    "A personal achievement will bring you satisfaction.",
    "You will overcome a challenge with ease.",
    "A happy event will bring joy to your life.",
    "You will be rewarded for your hard work.",
    "A positive change is coming your way.",
    "Your creativity will lead to new opportunities.",
    "You will find happiness in an unexpected place.",
    "A new relationship will bring joy to your life.",
    "Your efforts will be recognized and appreciated.",
    "A cherished dream will come true.",
    "You will receive good news from afar.",
    "A surprising turn of events will bring you joy.",
    "Your kindness will be rewarded in unexpected ways.",
    "A breakthrough is on the horizon.",
    "You will achieve a long-sought goal.",
    "An exciting opportunity will come your way.",
    "Your perseverance will pay off.",
    "A rewarding experience is just around the corner.",
    "A special event will bring you joy.",
    "You will find success in an unexpected place.",
    "Your hard work will bring about positive changes.",
    "An unexpected gift will bring happiness.",
    "A new chapter in your life is about to begin.",
    "You will receive a pleasant surprise soon.",
    "Your efforts will be recognized and appreciated.",
    "A cherished dream will soon be realized.",
    "You will find peace and joy in your endeavors.",
    "A positive change is just around the corner.",
    "Your creativity will lead to new opportunities.",
    "A significant achievement is on the way.",
    "You will overcome a challenge with grace.",
    "A joyful event will soon brighten your life.",
    "Your hard work will soon be rewarded.",
    "An exciting new venture is on the horizon.",
    "You will receive unexpected support in your endeavors.",
    "A special occasion will bring happiness and joy.",
    "You will discover new possibilities in your life.",
    "Your dedication will lead to success.",
    "An opportunity for growth is on its way.",
    "A positive change is coming to your life.",
    "You will find fulfillment in your endeavors.",
    "A new friendship will bring joy and support.",
    "You will soon experience a breakthrough.",
    "Your creativity will lead to new achievements.",
    "A rewarding opportunity is just around the corner.",
    "You will receive a pleasant surprise soon.",
    "An unexpected event will bring you joy and happiness.",
    "Your hard work will be recognized and celebrated.",
    "A special occasion will soon bring you great joy.",
    "You will find success in your upcoming ventures.",
    "A cherished wish will come true soon.",
    "You will discover new strengths within yourself.",
    "A significant achievement is on the horizon.",
    "Your kindness will lead to positive outcomes.",
    "An exciting new journey is about to begin.",
    "You will receive support from an unexpected source.",
    "A joyful event will bring happiness to your life.",
    "You will find fulfillment in a new endeavor.",
    "Your perseverance will soon pay off.",
    "A new opportunity will bring positive changes.",
    "You will experience a rewarding breakthrough.",
    "A special moment will soon bring you great joy.",
    "You will achieve a long-sought goal.",
    "A positive change is just around the corner.",
    "Your hard work will be recognized and celebrated.",
    "An unexpected gift will bring you happiness.",
    "A new beginning is on the horizon.",
    "You will find success in your future endeavors.",
    "A cherished dream will soon come true.",
    "You will discover new opportunities in your life.",
    "Your creativity will lead to great achievements.",
    "An exciting new chapter is about to begin.",
    "You will receive unexpected support and encouragement.",
    "A joyful event will soon brighten your life.",
    "Your hard work will soon be rewarded.",
    "A special occasion will bring you great joy.",
    "You will find peace and fulfillment in your endeavors.",
    "A positive change is coming your way.",
    "Your dedication and efforts will lead to success.",
    "A significant breakthrough is on the horizon.",
    "You will receive a pleasant surprise soon.",
    "An unexpected opportunity will bring you joy.",
    "Your creativity will open new doors for you.",
    "A rewarding experience is just around the corner.",
    "You will achieve a cherished goal.",
    "A new friendship will bring joy to your life.",
    "Your hard work will soon be recognized.",
    "A special event will bring you happiness.",
    "You will find success in your upcoming ventures.",
    "A cherished wish will soon be realized.",
    "You will discover new strengths within yourself.",
    "A significant achievement is on its way.",
    "Your kindness will lead to positive outcomes.",
    "An exciting new journey is on the horizon.",
    "You will receive support from an unexpected source.",
    "A joyful event will bring happiness to your life.",
    "You will find fulfillment in a new endeavor.",
    "Your perseverance will soon pay off.",
    "A new opportunity will bring positive changes.",
    "You will experience a rewarding breakthrough.",
    "A special moment will soon bring you great joy.",
    "You will achieve a long-sought goal.",
    "A positive change is just around the corner.",
    "Your hard work will be recognized and celebrated.",
    "An unexpected gift will bring you happiness.",
    "A new beginning is on the horizon.",
    "You will find success in your future endeavors.",
    "A cherished dream will soon come true.",
    "You will discover new opportunities in your life.",
    "Your creativity will lead to great achievements.",
    "An exciting new chapter is about to begin.",
    "You will receive unexpected support and encouragement.",
    "A joyful event will soon brighten your life.",
    "Your hard work will soon be rewarded.",
    "A special occasion will bring you great joy.",
    "You will find peace and fulfillment in your endeavors.",
    "A positive change is coming your way.",
    "Your dedication and efforts will lead to success.",
    "A significant breakthrough is on the horizon.",
    "You will receive a pleasant surprise soon.",
    "An unexpected opportunity will bring you joy.",
    "Your creativity will open new doors for you.",
    "A rewarding experience is just around the corner.",
    "You will achieve a cherished goal.",
    "A new friendship will bring joy to your life.",
    "Your hard work will soon be recognized.",
    "A special event will bring you happiness.",
    "You will find success in your upcoming ventures.",
    "A cherished wish will soon be realized.",
    "You will discover new strengths within yourself.",
    "A significant achievement is on its way.",
    "Your kindness will lead to positive outcomes.",
    "An exciting new journey is on the horizon.",
    "You will receive support from an unexpected source.",
    "A joyful event will bring happiness to your life.",
    "You will find fulfillment in a new endeavor.",
]

def get_fortune():
    """Returns a random fortune from the list."""
    return random.choice(FORTUNES)

def provide_fortune(name):
    """Returns a fortune with a personalized message."""
    fortune = get_fortune()
    return f"{name}, {fortune}"

def main():
    name = input("Enter your name: ")
    fortune = provide_fortune(name)
    print(f"Your fortune: {fortune}")

# Ensure this file runs as a script
if __name__ == "__main__":
    main()
